name: neuralforecast
channels:
  - conda-forge
  - pytorch
dependencies:
  - jupyterlab
  - matplotlib
  - numba
  - numpy>=1.21.6
  - optuna
  - pandas>=1.3.5
  - pytorch==2.0.0
  - pytorch-lightning>=2.0.0
  - pip
  - utilsforecast>=0.0.6
  - pip:
    - nbdev
    - black
    - "ray[tune]==2.6.3"
