name: neuralforecast
channels:
  - conda-forge
  - pytorch
dependencies:
  - jupyterlab
  - matplotlib
  - numpy>=1.21.6
  - pandas>=1.3.5
  - pytorch>=1.12.0
  - pytorch-lightning>=1.9.0,<2.0.0
  - pip
  - pip:
    - nbdev
    - "ray[tune]>=2.2.0"
