name: nixtla
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - hyperopt
  - matplotlib
  - numba
  - pandas
  - pip
  - pytorch
  - requests
  - statsmodels
  - scikit-learn
  - tqdm
  - xlrd
  - openpyxl
  - pip:
    - nbdev
    - pytorch-lightning>=1.3.0
    - torchinfo
    - py7zr
