name: neuralforecast
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - hyperopt
  - jupyterlab
  - matplotlib
  - numba
  - numpy>=1.21.6
  - optuna
  - pandas>=1.3.5
  - pyarrow
  - pytorch>=2.0.0
  - pytorch-cuda>=11.8
  - pytorch-lightning>=2.0.0
  - pip
  - pip:
    - nbdev
    - black
    - polars
    - "ray[tune]>=2.2.0"
    - utilsforecast>=0.0.24
