name: neuralforecast
channels:
  - pytorch
  - conda-forge
dependencies:
  - coreforecast>=0.0.6
  - cpuonly
  - fsspec
  - gitpython
  - hyperopt
  - jupyterlab
  - matplotlib
  - numba
  - numpy>=1.21.6
  - optuna
  - pandas>=1.3.5
  - pyarrow
  - pytorch>=2.0.0
  - pytorch-lightning>=2.0.0
  - pip
  - s3fs
  - snappy<1.2.0
  - pip:
    - nbdev
    - black
    - polars
    - ray[tune]>=2.2.0
    - utilsforecast>=0.0.25
